spring:
  application:
    name: backend
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  mail:
    host: smtp.gmail.com
    port: 587
    username: scheduleaiagent26@gmail.com
    password: ${SPRING_MAIL_PASSWORD_PROD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${SPRING_DATASOURCE_USERNAME_PROD}
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST_PROD}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME_PROD}
    password: ${SPRING_RABBITMQ_PASSWORD_PROD}
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
app:
  jwt-secret: ${APP_JWT_SECRET_PROD}
  jwt-expiration-milliseconds: 30000000
  jwt-refresh-expiration-milliseconds: 3000000000
  base-url: http://production.example.com
  cors:
    allowed-origins: http://production.frontend.com
server:
  servlet:
    context-path: /api/v1
  port: 8000
springdoc:
  override-with-generic-response: false
minio:
  url: http://minio.production:9000
  access:
    key: ${MINIO_ACCESS_KEY_PROD}
    secret: ${MINIO_ACCESS_SECRET_PROD}
  bucket:
    name: edtech-content-production
janus:
  server:
    url: ${JANUS_SERVER_URL_PROD}
